### PR TITLE
Let the users remove entries

### PR DESCRIPTION
**Pull request by Kerollmops**

### CODE REVIEW

**Comment by jedisct1** [comment]
Keys should also be removed from the evicted sets.

And for consistency, if we add a `remove` operation, we should probably add a `removed` counter as well.

**Comment by jedisct1** [comment]
Thank you!

**Comment by Kerollmops** [comment]
Do you plan to bump the crate version?

**Comment by jedisct1** [comment]
Done.

**Comment by Kerollmops** [comment]
It doesn't seems like the v0.2.3 contains these changes.

EDIT: The v0.2.4 did.

**Pull request merged**
