### PR TITLE
Implement IntoIterator on ArcCache

### PR DESCRIPTION
**Pull request by ghost**
This allows users to iterate over the items in the cache, which may be useful for debugging purposes.

### CODE REVIEW

**Comment by jedisct1** [comment]
Sure, that can be useful!

Thank you for contributing this!

Do you need a new release to be tagged urgently?

**Comment by ghost** [comment]
Thank you for this crate and for taking a look at this so quickly! If you could tag a release sometime during the next week or so that would be great, otherwise we'll just depend on the git repository.

**Comment by jedisct1** [comment]
Done!

**Comment by ghost** [comment]
Thank you so much!

**Pull request merged**
